#!/usr/bin/env perl

use strict;
use warnings;

use Test::Deep;
use Test::More;
use DBIx::Class::ResultSet;

use Devel::Dwarn;

my @tests = (
   # SCALAR SCALAR
   ['frew', 'bar', ['frew', 'bar']],
   ['frew', 'frew', 'frew'],

   # SCALAR ARRAY
   [undef, ['frew'], ['frew']],
   ['frew', ['bar'], ['frew', 'bar']],
   ['frew', ['frew'], ['frew']],
   ['frew', [{frew=> 1}], [{frew=> 1}]],
   ['frew', [{bar=> 1}], ['frew', {bar=> 1}]],

   # SCALAR HASH
   [undef, {frew => 1}, {frew => 1}],
   ['frew', {frew => 1}, {frew => 1}],
   ['bar', {frew => 1}, ['bar', {frew => 1}]],

   # ARRAY SCALAR
   [['frew'], undef, ['frew']],
   [['bar'], 'frew', ['bar', 'frew']],
   [['frew'], 'frew', ['frew']],

   # ARRAY ARRAY
   [['frew'], [], ['frew']],
   [[], ['frew'], ['frew']],
   [['frew'], ['bar'], ['frew', 'bar']],
   [['frew', 'biff'], ['bar', 'biff'], ['frew', 'bar', 'biff']],

   # ARRAY HASH
   [['frew'], {'frew' => 'bar'}, { 'frew' => 'bar'}],
   [['biff'], {'frew' => 'bar', biff => 1}, { 'frew' => 'bar', biff => 1}],

   # HASH SCALAR
   [{frew => 1}, undef, {frew => 1}],
   [{frew => 1}, 'frew', {frew => 1}],
   [{frew => 1}, 'bar', [{frew => 1}, 'bar']],

   # HASH ARRAY
   [{frew => 1}, [], [{frew => 1}]],
   [{frew => 1}, ['frew'], [{frew => 1}]],
   [{frew => 1}, ['bar'], [{frew => 1}, 'bar']],

);

for ( @tests ) {
   my $merged = DBIx::Class::ResultSet::_merge_attr(undef, $_->[0], $_->[1]);
   use Devel::Dwarn;

   #Dwarn $merged;
   cmp_deeply($merged, $_->[2])
}


done_testing;
